### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by aureliusm** [ramasilveyra/mjml-loader#10]
Hi, are you planning to add webpack 4 support?

Currently this error occurs with webpack 4:

```
(node:8817) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
/node_modules/tde-webpack-mjml-plugin/src/webpack-mjml-store.js:68
      let response = mjml2html(contents);
                     ^

TypeError: mjml2html is not a function
    at /node_modules/tde-webpack-mjml-plugin/src/webpack-mjml-store.js:68:22
    at /node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by philiiiiiipp** [comment]
I am not sure if you are still interested in this, but https://github.com/DatHuis/mjml-loader
